### PR TITLE
fix: data type mismatch in the `subscriptions` migration

### PR DESCRIPTION
**Pull request by ibnsultan**
## What kind of change does this PR introduce?

- [x] Bugfix 
- [ ] Feature 
- [ ] Code style update 
- [x] Refactor
- [ ] Build-related changes

## Description
This PR addresses an issue with the foreign key constraint between the `subscriptions` and `plans` tables. The constraint failed due to a data type mismatch between the `plan_id` in the `subscriptions` table and the `id` in the `plans` table.

### Fixes Implemented:
- **Reordered Migrations**: The migration for the `subscription` table was reordered to run after the `plans` table, ensuring that the foreign key reference is established correctly during the migration process.
- **Data Type Mismatch Fix**: Adjusted the data type of the `plan_id` in the `subscriptions` table to match that of the `id` in the `plans` table, resolving the constraint error.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Related Issue

None

### CODE REVIEW

**Review by bobbyiliev — APPROVED** [review]
This looks good to me! I'll let @tnylea also check it out before merging!

**Comment by adamthomason** [comment]
In addition to this, there's a further issue in that the *_create_plans_table.php file has a later timestamp than the *_create_subscrpitions_table.php which causes a failure when migration. The subscriptions table references the plans table in its migration, so the plans table should be created first.

**Comment by vipxr** [comment]
I had the same problem and fixed it myself and wanted to fix it here too but you did it thank you

**Comment by tnylea** [comment]
Looks great to me. Thanks guys!

@adamthomason would you mind submitting a PR for that issue with the migration you were experiencing. Thanks.

**Pull request merged**
