### PR TITLE
Match default laravel config better. Main reason it to user using php…

### PR DESCRIPTION
**Pull request by timhaak**
Hi

I wanted to rather use phpredis over predis.

But there was no env variable to allow this.

So I've gone over what a default install database config looks like and added any of the missing settings.

Though I've left it so that predis is still the default. But you can now override it with.

REDIS_CLIENT

### CODE REVIEW

**Comment by timhaak** [comment]
I've done the same for the app.php config.

I've also published trustedproxy.php and added an env variable to set this.

This is needed if you are running behind a proxy providing https and you are hitting http.

**Comment by timhaak** [comment]
Added missing symlink from ./public/storage to ../storage/app/public

This fixed the missing files for links like this /storage/themes/February2018/mFajn4fwpGFXzI1UsNH6.png

**Comment by tnylea** [comment]
@timhaak Thanks man! This is great! Doing a quick check now to make sure everything is still working with this PR. I'll do a check in the next 15 min. and get back to you.

Appreciate the PR 😉

**Comment by tnylea** [comment]
Excellent!

Merging in. Thanks @timhaak

**Pull request merged**
