### PR TITLE
Development

### PR DESCRIPTION
**Pull request by dschiffer12**

### CODE REVIEW

**Comment by thinkverse** [comment]
Not sure this PR was meant to be pushed to Wave. 🤔 Also, your `.env` file is getting tracked, which should **never** be tracked and pushed into version control, those contain secrets that should not be publicly available, that's a huge security risk. I recommend stopping tracking it immediately and reading "[Removing sensitive data from a repository](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository)" from GitHubs' documentation on how to proceed next.

@bobbyiliev you can close this PR. 👍

**Comment by dschiffer12** [comment]
Thanks for the message. I was troubleshooting through some connectivity
issues. I switched to a private repo yesterday for my main project, and
just deleted the old one.

**Comment by thinkverse** [comment]
That’s great an all, but I’d still suggest refreshing any secret keys and switching any passwords that was in the file. 👍 As soon as it has been public you can be sure some bot has snatched up the credentials.

**Comment by dschiffer12** [comment]
Thanks for the tip, they were all temporary passwords and credentials.

**Pull request closed without merging**
