### PR TITLE
Add MIT license

### PR DESCRIPTION
**Pull request by bobbyiliev**

### CODE REVIEW

**Review by glaukiol1 — APPROVED** [review]
An MIT license is a good choice, but you have to consult the devs on what they want. But for me, the MIT license is my favorite, approved

**Review by hajiparwani — APPROVED** [review]

**Review by orangeskyfighter — APPROVED** [review]

**Review by RICHIEHASTY — APPROVED** [review]

**Review by NIKKUGOLA — COMMENTED** [review]
👍

**Review by ali13691369 — APPROVED** [review]
Hi

**Comment by ali13691369** [comment]
Hi

**Comment by SyedAsadullah19** [comment]
Hello I am new to github and I don't know how to use it

**Review by ali13691369 — APPROVED** [review]

**Review by ali13691369 — APPROVED** [review]
Hi

**Comment by tnylea** [comment]
Thanks @bobbyiliev, you rock ;)

**Comment by yashaggarwa** [comment]
GitHub was very simple

**Comment by yashaggarwa** [comment]
Plz tell me what we have to do in GitHub

**Pull request merged**
