### PR TITLE
Update Wave with Laravel 9.

### PR DESCRIPTION
**Pull request by thinkverse**
This PR updates Wave's Laravel application to a base Laravel 9 version and also bumps all dependencies to support Laravel 9. This is in response to #46 and my own desire to update the base Laravel app to a newer version.

Updating to Laravel 9 will force a minimum of PHP 8.0.2, 7.4 and lesser will not work anymore since Laravel 9 forces ^8.0.2.

PR is not fully tested yet, hence why it's being submitted as a draft. Testers are more than welcome. To test, clone this PR and report any issues found back here and they'll be resolved.

### Tested and working on PHP 8.1+

- [x] Authentication
- [x] User Profiles
- [x] User Impersonation
- [x] Subscriptions
- [x] Subscriptions Plans
- [x] User Roles
- [x] Notifications
- [x] Announcements
- [x] Blog
- [X] API
- [X] Voyager
- [x] Themes

### CODE REVIEW

**Comment by titonova** [comment]
lmaoo, thank goodness I saw this. I was just about to start updating wave to Laravel 9 By myself lolll

**Comment by titonova** [comment]
Im so happy !!!

**Comment by MrGKanev** [comment]
Is there an ETA for this PR?

**Comment by thinkverse** [comment]
> Is there an ETA for this PR?

Not from my point of view. It's up to the @thedevdojo team when or even if this gets merged.

If you want to use Laravel 9 instead of using Laravel 8. I've released [Surf](https://github.com/thinkverse/surf) in the meantime. It's a fork of Wave that's in essence just this PR merged or you can download this PR directly from my Wave fork, or wait until it's potentially merged.

**Comment by Gerardlc** [comment]
@bobbyiliev any possibilities to merge this one so we can benefit from version 9?

**Review by bobbyiliev — APPROVED** [review]
This is amazing! Thank you for putting this together @thinkverse 🚀 

Just finished testing it and it looks good!

**Pull request merged**
