### PR TITLE
UI tweaks, script tweak and bug fixes

### PR DESCRIPTION
**Pull request by 7Skiez**
Great work, Thought it'd be cool to add some UI changes, little bug fixes and script improvements.

### CODE REVIEW

**Comment by bilalnurcan47** [comment]
[]()

**Comment by tnylea** [comment]
@7Skiez thanks for the PR. The code looks good and I appreciate the fixes; however, it does appear that these UI tweaks have messed up some alignment on the homepage. Here's is quick screencast:

https://www.loom.com/share/6a2d81836ec74ba6ab35a3f77e1199b1

Your branch is the one in the first tab, compare that to the 2nd tab and it looks like there are some alignment issues. If you can get this fixed, I can take another look and then get this merged in.

Thanks again!

**Review by tnylea — CHANGES_REQUESTED** [review]
See the last comment in the thread. There are a few alignment issues that this PR has created:

https://www.loom.com/share/6a2d81836ec74ba6ab35a3f77e1199b1

Thanks!

**Comment by 7Skiez** [comment]
> See the last comment in the thread. There are a few alignment issues that this PR has created:
> 
> https://www.loom.com/share/6a2d81836ec74ba6ab35a3f77e1199b1
> 
> Thanks!

@tnylea Thanks man, Pleasure to be working on the project, Sorry I forgot changing the promo image in the seeders, The whole point of this UI change was to add a floating boat/ship to go with the wave/voyager paradigm (I'm not sure if this could be a new theme or something you could configure through admin). I've added a few more demo ship images in the public theme directory, They're interchangeable through the admin panel.
wave_ships_demo
I changed the width for dropdown containers for this not to happen when the text/content gets smaller : 
w-screen_vs_w-max
However if you didn't like the look of it so far, I could just put in the changes for code (excluding UI).

**Comment by tnylea** [comment]
@7Skiez Love those images!

thanks for this PR. I'll be taking a look at it today. Looks super cool! And thanks for the menu UI updates.

**Comment by 7Skiez** [comment]
This piece of code will help fixing the sequence and auto incrementing problem on PostgreSQL the-control-group/voyager#3563 after seeding the pgsql database, This will help fixing the unique violation error and allows normal use.

**Comment by tnylea** [comment]
@7Skiez Thanks for these fixes. Loving it!

Before I merge this in, I want to guarantee that it's available to run on PHP7 and PHP8, currently, this PR has a `composer.lock` file that requires `spatie/macroable` locked at 2.0 which requires PHP 8.

Here's the error screen that I get when I try and install a fresh copy from your PR branch:

CleanShot 2021-05-27 at 21 43 45@2x

@bobbyiliev and I are working to get some more tests into the system so that way stuff like this can be checked when a PR is opened. I might suggest trying to remove `spatie/ray` or `macroable` from your composer.json.

Hope you understand, I want to make sure that as many people who pull the latest version of Wave are able to install it, even if they are on PHP7.

Thanks! Keep me posted with the progress on this. Appreciate all the help.

**Comment by 7Skiez** [comment]
@tnylea Hi, I got the same error running php 8 on my machine, I'll revert back the lock file and make a new commit.

image

**Comment by 7Skiez** [comment]
> CleanShot 2021-05-27 at 21 43 45@2x

Try running ``composer install --ignore-platform-reqs``  instead, It helps with this issue.

**Comment by 7Skiez** [comment]
@tnylea Please checkout thedevdojo/themes#3 I tried adding a radio button to be able to switch between layouts, and found this bug, Now I need this merged in before I send one last commit.

**Comment by 7Skiez** [comment]
Added hero layout radio button switch inside admin, theme options.

image

image

**Review by bobbyiliev — COMMENTED** [review]
I am going to close this PR as it now has quite a bit of merge conflicts.

I believe that you've cherry-picked some of the fixes from here. Thank you for your contribution!

**Pull request closed without merging**
